networks:
  backend:
    external: true
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=${APP_KEY}
            - APP_URL=${APP_URL}
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE}
            - DISPLAY_TIMEZONE=America/Sao_Paulo
        volumes:
           - /appdata/speedtest/config:/config
           - /appdata/speedtest/keys:/config/keys
        networks:
           - backend
