---
- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/rflpazini

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
