---
- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/rflpazini
    - CloudFlare:
        - abbr: CF
          href: https://dash.cloudflare.com/8e21c51ad2be85f30ac65a6c6ce3024e/rfl.sh